### ISSUE TITLE
Team IDs

### ISSUE THREAD

**Issue by liamhawkins** [zackthoutt/nfl-player-stats#4]
Regarding future improvement 2 : 

> Extract Team IDs to make relating players across teams and games easier

Did you have in mind a Team ID other than their three letter code (e.g. DAL)? Perhaps a unique team ID for each year of a franchise, or an ID for each unique group of players? This could be used to distinguish high-performing vs. low-performing teams that are part of the same franchise but played in different seasons.

**Comment by zackthoutt** [comment]
That's a good point. We can always extract an ID for a franchise-year combo in pre-processing for a model, it doesn't necessarily need to be part of the raw data. What do you think? 

There's no harm in putting the franchise-year team ID in the raw data though.

**Comment by liamhawkins** [comment]
I'm agnostic as to whether it should be in the raw data or done through pre-processing. The one upside to raw data I can see is if you wanted to update the Kaggle dataset, in which it would be more "complete" (?).

**Comment by zackthoutt** [comment]
Ya, maybe let's add them since it will be useful for certain types of models and data visualizing. What's a good email for you? I'm creating a slack channel. There is another person who contacted me and wants to help with the project.

**Comment by liamhawkins** [comment]
liamhawkinscu@gmail.com

**Comment by zackthoutt** [comment]
Moving this discussion to a more general discussion about player, game, and team IDs.

https://github.com/zackthoutt/nfl-player-stats/issues/8
